### ISSUE TITLE
star.py does not work with subtomo star file

### ISSUE THREAD

**Issue by pherepanov** [asarnow/pyem#112]
star.py does not seem to be able to interpret a subtomo star file (the same installation works fine with star files from an SPA project). The error is pasted below. 

/camp/home/cherepp/.conda/envs/pyem_beta/lib/python3.8/site-packages/pyem/star.py:567: FutureWarning: Columnar iteration over characters will be deprecated in future releases.
  df[UCSF.IMAGE_INDEX], df[UCSF.IMAGE_PATH] = \
Traceback (most recent call last):
  File "/camp/home/cherepp/.conda/envs/pyem_beta/bin/star.py", line 372, in <module>
    sys.exit(main(parser.parse_args()))
  File "/camp/home/cherepp/.conda/envs/pyem_beta/bin/star.py", line 37, in main
    df = pd.concat((star.parse_star(inp, augment=args.augment) for inp in args.input), join="inner")
  File "/camp/home/cherepp/.conda/envs/pyem_beta/lib/python3.8/site-packages/pandas/core/reshape/concat.py", line 271, in concat
    op = _Concatenator(
  File "/camp/home/cherepp/.conda/envs/pyem_beta/lib/python3.8/site-packages/pandas/core/reshape/concat.py", line 326, in __init__
    objs = list(objs)
  File "/camp/home/cherepp/.conda/envs/pyem_beta/bin/star.py", line 37, in <genexpr>
    df = pd.concat((star.parse_star(inp, augment=args.augment) for inp in args.input), join="inner")
  File "/camp/home/cherepp/.conda/envs/pyem_beta/lib/python3.8/site-packages/pyem/star.py", line 450, in parse_star
    augment_star_ucsf(df, inplace=True)
  File "/camp/home/cherepp/.conda/envs/pyem_beta/lib/python3.8/site-packages/pyem/star.py", line 567, in augment_star_ucsf
    df[UCSF.IMAGE_INDEX], df[UCSF.IMAGE_PATH] = \
ValueError: not enough values to unpack (expected 2, got 1)

**Comment by asarnow** [comment]
I know, and it's a problem for me too now. I'm working on a branch called `starfile` to switch from my STAR parser to the teamtomo one, which will resolve the problem.

**Comment by asarnow** [comment]
Resolved by [7482e60](https://github.com/asarnow/pyem/commit/7482e60bf32aa4f422f4bae23c5ea51110dbfc63).

Removing duplicate particles, recentering particle coordinates, normalizing star files, and printing star file information / statistics are all tested. Please create a new issue if you run into anything that doesn't work in 3D!
