### ISSUE TITLE
Cryosparc 2 to star

### ISSUE THREAD

**Issue by dhaselb** [asarnow/pyem#16]
Hi  I am trying to convert a cs file from cryosparc 2 to relion with your script and I am getting: 

python csparc2star.py particles_selected.cs test.star
Traceback (most recent call last):
  File "csparc2star.py", line 115, in <module>
    sys.exit(main(parser.parse_args()))
  File "csparc2star.py", line 67, in main
    df = metadata.parse_cryosparc_2_cs(cs, passthrough=args.passthrough, minphic=args.minphic)
  File "/home/david.haselbach/Downloads/pyem-master/pyem/metadata.py", line 249, in parse_cryosparc_2_cs
    df[star.Relion.DEFOCUSANGLE] = np.rad2deg(np.arctan2(df[star.Relion.DEFOCUSV], df[star.Relion.DEFOCUSU]))
  File "/home/david.haselbach/anaconda2/lib/python2.7/site-packages/pandas/core/frame.py", line 2685, in __getitem__
    return self._getitem_column(key)
  File "/home/david.haselbach/anaconda2/lib/python2.7/site-packages/pandas/core/frame.py", line 2692, in _getitem_column
    return self._get_item_cache(key)
  File "/home/david.haselbach/anaconda2/lib/python2.7/site-packages/pandas/core/generic.py", line 2486, in _get_item_cache
    values = self._data.get(item)
  File "/home/david.haselbach/anaconda2/lib/python2.7/site-packages/pandas/core/internals.py", line 4115, in get
    loc = self.items.get_loc(item)
  File "/home/david.haselbach/anaconda2/lib/python2.7/site-packages/pandas/core/indexes/base.py", line 3065, in get_loc
    return self._engine.get_loc(self._maybe_cast_indexer(key))
  File "pandas/_libs/index.pyx", line 140, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 162, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 1492, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 1500, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'rlnDefocusV'

Any Idea what could be the issue?

**Comment by asarnow** [comment]
There are a lot of fixes since this time, pertaining to various job types in cryoSPARC2 as well as general robustness in unexpected cases. It should be working now - reopen if not!
