### ISSUE TITLE
Error running csparc2star.py

### ISSUE THREAD

**Issue by hansenbry** [asarnow/pyem#25]
Hi I'm trying to export particles from cryosparc to then import into relion.  I'm having an issue when running the csparc2star.py command.  I get the following message:

[hansenbry@D01868462 J86]$ csparc2star.py cryosparc_P4_J86_005_particles.cs cryosparc_P4_J86_005_particles.star
Traceback (most recent call last):
  File "/home/hansenbry/EMsoftware/pyem/csparc2star.py", line 28, in <module>
    from pyem import metadata
  File "/home/hansenbry/EMsoftware/pyem/pyem/__init__.py", line 3, in <module>
    from . import metadata
  File "/home/hansenbry/EMsoftware/pyem/pyem/metadata.py", line 24, in <module>
    from . import star
  File "/home/hansenbry/EMsoftware/pyem/pyem/star.py", line 31, in <module>
    from pyem.util import rot2euler
  File "/home/hansenbry/EMsoftware/pyem/pyem/util/__init__.py", line 3, in <module>
    from .util import *
  File "/home/hansenbry/EMsoftware/pyem/pyem/util/util.py", line 25, in <module>
    from .. import geom
  File "/home/hansenbry/EMsoftware/pyem/pyem/geom/__init__.py", line 4, in <module>
    from .geom import *
  File "/home/hansenbry/EMsoftware/pyem/pyem/geom/geom.py", line 20, in <module>
    from .quat import distq
  File "/home/hansenbry/EMsoftware/pyem/pyem/geom/quat.py", line 27, in <module>
    qconj = np.vectorize(_qconj, signature="(m),(m)->(m)")
TypeError: __init__() got an unexpected keyword argument 'signature'

I get this message if I try to run it without any arguments as well.  I just did a git clone and build today (1/16/19) so I'm assuming this is the newest code base.  Thanks for any tips

**Comment by asarnow** [comment]
Same as #20 - old version of numpy. Please update numpy to a recent version.
