### ISSUE TITLE
New csparc2star.py error   

### ISSUE THREAD

**Issue by egiudice** [asarnow/pyem#29]
Hello 
I'm trying to export particules coordinates form cryospark 2.5 to Relion3
I install pyem using miniconda (I first download and instal it)
, create symlink in ~/bin
but when I try csparc2star I got the following errors :

csparc2star.py particles_selected.cs test.star
Traceback (most recent call last):
  File "/home/emmanuel/bin/csparc2star.py", line 28, in <module>
    from pyem import metadata
  File "/home/emmanuel/Software/pyem/pyem/__init__.py", line 3, in <module>
    from . import metadata
  File "/home/emmanuel/Software/pyem/pyem/metadata.py", line 25, in <module>
    from . import star
  File "/home/emmanuel/Software/pyem/pyem/star.py", line 31, in <module>
    from pyem.util import rot2euler
  File "/home/emmanuel/Software/pyem/pyem/util/__init__.py", line 3, in <module>
    from .util import *
  File "/home/emmanuel/Software/pyem/pyem/util/util.py", line 25, in <module>
    from .. import geom
  File "/home/emmanuel/Software/pyem/pyem/geom/__init__.py", line 4, in <module>
    from .geom import *
  File "/home/emmanuel/Software/pyem/pyem/geom/geom.py", line 22, in <module>
    from .quat_numba import qslerp
  File "/home/emmanuel/Software/pyem/pyem/geom/quat_numba.py", line 153, in <module>
    "(m)->(m), (m), (m), (m)", nopython=True, cache=False)
  File "/home/emmanuel/miniconda2/lib/python2.7/site-packages/numba/npyufunc/decorators.py", line 179, in wrap
    guvec.add(fty)
  File "/home/emmanuel/miniconda2/lib/python2.7/site-packages/numba/npyufunc/ufuncbuilder.py", line 194, in add
    self.nb_func, targetoptions, sig)
  File "/home/emmanuel/miniconda2/lib/python2.7/site-packages/numba/npyufunc/ufuncbuilder.py", line 128, in _compile_element_wise_function
    cres = nb_func.compile(sig, **targetoptions)
  File "/home/emmanuel/miniconda2/lib/python2.7/site-packages/numba/npyufunc/ufuncbuilder.py", line 77, in compile
    return self._compile_core(sig, flags, locals)
  File "/home/emmanuel/miniconda2/lib/python2.7/site-packages/numba/npyufunc/ufuncbuilder.py", line 112, in _compile_core
    flags=flags, locals=locals)
  File "/home/emmanuel/miniconda2/lib/python2.7/site-packages/numba/compiler.py", line 926, in compile_extra
    return pipeline.compile_extra(func)
  File "/home/emmanuel/miniconda2/lib/python2.7/site-packages/numba/compiler.py", line 374, in compile_extra
    return self._compile_bytecode()
  File "/home/emmanuel/miniconda2/lib/python2.7/site-packages/numba/compiler.py", line 857, in _compile_bytecode
    return self._compile_core()
  File "/home/emmanuel/miniconda2/lib/python2.7/site-packages/numba/compiler.py", line 844, in _compile_core
    res = pm.run(self.status)
  File "/home/emmanuel/miniconda2/lib/python2.7/site-packages/numba/compiler_lock.py", line 32, in _acquire_compile_lock
    return func(*args, **kwargs)
  File "/home/emmanuel/miniconda2/lib/python2.7/site-packages/numba/compiler.py", line 255, in run
    raise patched_exception
TypeError: Failed in nopython mode pipeline (step: analyzing bytecode)

I also try the general installation with the same result.

**Comment by asarnow** [comment]
Please track the release branch instead of master - `git checkout release`.

**Comment by egiudice** [comment]
thanks a lot
