### ISSUE TITLE
Trouble using csparc2star.py 

### ISSUE THREAD

**Issue by olibclarke** [asarnow/pyem#43]
Hi Dan,
I am trying to use `csparc2star.py` on the particles.cs file output from an old NU-refine job. The NU-refine job was run using particles imported from relion 3.0.x; the cryosparc version at the time was 2.5.2. When I run the job, I get an error complaining that it can't find the OpticsGroup column. Any ideas as to what I am doing wrong?

Cheers
Oli

`(pyem) user@narwhal:~$ csparc2star.py cryosparc_P16_J504_007_particles.cs cryosparc_P16_J504_007_particles.star
Traceback (most recent call last):
  File "/home/user/software/pyem/csparc2star.py", line 110, in <module>
    sys.exit(main(parser.parse_args()))
  File "/home/user/software/pyem/csparc2star.py", line 83, in main
    star.write_star(args.output, df, resort_records=True)
  File "/home/user/software/pyem/pyem/star.py", line 419, in write_star
    gb = df.groupby(Relion.OPTICSGROUP)
  File "/home/user/software/miniconda3/envs/pyem/lib/python3.8/site-packages/pandas/core/frame.py", line 5801, in groupby
    return groupby_generic.DataFrameGroupBy(
  File "/home/user/software/miniconda3/envs/pyem/lib/python3.8/site-packages/pandas/core/groupby/groupby.py", line 402, in __init__
    grouper, exclusions, obj = get_grouper(
  File "/home/user/software/miniconda3/envs/pyem/lib/python3.8/site-packages/pandas/core/groupby/grouper.py", line 598, in get_grouper
    raise KeyError(gpr)
KeyError: 'rlnOpticsGroup'`

**Comment by asarnow** [comment]
Fixed by 4581c81
