### ISSUE TITLE
csparc2star.py error

### ISSUE THREAD

**Issue by istv01** [asarnow/pyem#7]
Hi,

Just installed pyem with EMan2.2 but csparc2star.py gives an error:

Traceback (most recent call last):
  File "./csparc2star.py", line 25, in <module>
    import pandas as pd
  File "/progs/EMAN2/lib/python2.7/site-packages/pandas/__init__.py", line 42, in <module>
    from pandas.core.api import *
  File "/progs/EMAN2/lib/python2.7/site-packages/pandas/core/api.py", line 10, in <module>
    from pandas.core.groupby import Grouper
  File "/progs/EMAN2/lib/python2.7/site-packages/pandas/core/groupby.py", line 49, in <module>
    from pandas.core.frame import DataFrame
  File "/progs/EMAN2/lib/python2.7/site-packages/pandas/core/frame.py", line 74, in <module>
    from pandas.core.series import Series
  File "/progs/EMAN2/lib/python2.7/site-packages/pandas/core/series.py", line 3042, in <module>
    import pandas.plotting._core as _gfx  # noqa
  File "/progs/EMAN2/lib/python2.7/site-packages/pandas/plotting/__init__.py", line 17, in <module>
    from pandas.plotting._core import boxplot
  File "/progs/EMAN2/lib/python2.7/site-packages/pandas/plotting/_core.py", line 40, in <module>
    if _mpl_ge_1_5_0():
  File "/progs/EMAN2/lib/python2.7/site-packages/pandas/plotting/_compat.py", line 40, in _mpl_ge_1_5_0
    return (matplotlib.__version__ >= LooseVersion('1.5') or
  File "/progs/EMAN2/lib/python2.7/distutils/version.py", line 296, in __cmp__
    return cmp(self.version, other.version)
AttributeError: 'unicode' object has no attribute 'version'

**Comment by asarnow** [comment]
I believe my requirements.txt isn't specific enough.

Can you update matplotlib, using `pip install --upgrade matplotlib`? I don't believe any other packages *have* to be updated.

**Comment by istv01** [comment]
Thanks, that did update several packages not only matplotlib. The program seems to start ok now.
